# Generated by Django 2.0.1 on 2018-06-24 18:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Vehicles', 'Vehicles'), ('Properties', 'Properties'), ('Stationary', 'Stationary'), ('Fashion', 'Fashion'), ('Other', 'Other')], max_length=15)),
                ('item_type', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('posted_on', models.DateTimeField(default=datetime.datetime(2018, 6, 24, 23, 55, 38, 891744))),
                ('interested_count', models.IntegerField(default=0)),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.Advertisement')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=300)),
                ('message_time', models.DateTimeField(default=datetime.datetime(2018, 6, 24, 23, 55, 38, 891744))),
                ('chat_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx.ChatBox')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
